DROP TABLE IF EXISTS user;
CREATE TABLE user
(id int AUTO-INCREMENT PRIMARY KEY,
 name VARCHAR(50) NOT NULL,
 password VARCHAR(50) NOT NULL,
 loggedIn BIT DEFAULT 1
);

DROP TABLE IF EXISTS customer;
CREATE TABLE customer
(id int AUTO-INCREMENT PRIMARY KEY,
 name VARCHAR(50) NOT NULL,
 surname VARCHAR(50) NOT NULL,
 email VARCHAR(50) NOT NULL
);